### ISSUE TITLE
index out of bounds

### ISSUE THREAD

**Issue by q1vs5k5** [CnybTseng/JDE#1]
Thank you very much for sharing your project, when i run train.sh I encountered a bug as follows：
Traceback (most recent call last):
  File "train.py", line 208, in <module>
    train(args)
  File "train.py", line 173, in train
    loss, metrics = model(images.to(device), targets.to(device), size)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./JDE/darknet.py", line 270, in forward
    return self.criterion(outputs, targets, size, self.classifier)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./JDE/yolov3.py", line 147, in forward
    outputs = super().forward(xs)
  File "./JDE/yolov3.py", line 46, in forward
    zip(xs,self.anchor_masks)]
  File "./JDE/yolov3.py", line 45, in <listcomp>
    return [self.__decoder(x,self.anchors[mask,:]) for (x,mask) in \
IndexError: index 9 is out of bounds for dimension 0 with size 9

This is my anchors information, which is generated by default parameters：
6 17
9 28
13 39
16 49
24 68
35 100
53 150
85 232
158 392

May I have the pleasure to solve this problem with your help?

**Comment by CnybTseng** [comment]
> Thank you very much for sharing your project, when i run train.sh I encountered a bug as follows：
> Traceback (most recent call last):
> File "train.py", line 208, in
> train(args)
> File "train.py", line 173, in train
> loss, metrics = model(images.to(device), targets.to(device), size)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
> result = self.forward(*input, **kwargs)
> File "./JDE/darknet.py", line 270, in forward
> return self.criterion(outputs, targets, size, self.classifier)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
> result = self.forward(*input, **kwargs)
> File "./JDE/yolov3.py", line 147, in forward
> outputs = super().forward(xs)
> File "./JDE/yolov3.py", line 46, in forward
> zip(xs,self.anchor_masks)]
> File "./JDE/yolov3.py", line 45, in
> return [self.__decoder(x,self.anchors[mask,:]) for (x,mask) in
> IndexError: index 9 is out of bounds for dimension 0 with size 9
> 
> This is my anchors information, which is generated by default parameters：
> 6 17
> 9 28
> 13 39
> 16 49
> 24 68
> 35 100
> 53 150
> 85 232
> 158 392
> 
> May I have the pleasure to solve this problem with your help?

JDE has 12 anchors. You should set anchors like this:
6 16
8 23
11 32
16 45
21 64
30 90
43 128
60 180
85 255
120 360
170 420
340 320
Please save anchor parameters as anchors.txt and put it under training workspace directory, or modify anchor_masks setting in yolov3.py. For example:

self.anchor_masks = self.LongTensor(((6,7,8,),
            (3,4,5),(0,1,2)))

**Comment by q1vs5k5** [comment]
thank you very much.
