### ISSUE TITLE
about result

### ISSUE THREAD

**Issue by q1vs5k5** [CnybTseng/JDE#2]
This is a great project, thank you again for open it. I found that the results were not satisfactory after I trained for 50 epochs according to the default parameters of train.sh, so I want to communicate with you how to improve the performace? Looking forward to your reply!
![image](https://user-images.githubusercontent.com/36632724/94334942-76ef4f80-000a-11eb-8cb1-caad8762bf92.png)

**Comment by CnybTseng** [comment]
Use $ROOT/tools/train.py instead of $ROOT/train.py please.
